id: P004335
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN4311
  title: གཉུག་སེམས་སྐོར་གསུམ་དང་གཞུང་སྤྱིའི་དཀའ་གནད།
  author: ''
  volumes:
    86f57f98c2a544c19e5af5fde9074ef4:
      image_group_id: I3CN4330
      title: ''
      volume_number: 1
      total_pages: 460
      base_file: v001.txt
